/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AppRouteImport } from './routes/_app'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AppVendorsRouteImport } from './routes/_app/vendors'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppStoreLocationsRouteImport } from './routes/_app/store-locations'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPublishingRouteImport } from './routes/_app/publishing'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppPricingApprovalRouteImport } from './routes/_app/pricing-approval'
import { Route as AppMediaRouteImport } from './routes/_app/media'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBatchesRouteImport } from './routes/_app/batches'
import { Route as publicVisitRouteImport } from './routes/(public)/visit'
import { Route as publicShopRouteImport } from './routes/(public)/shop'
import { Route as publicGuidesRouteImport } from './routes/(public)/guides'
import { Route as publicFaqRouteImport } from './routes/(public)/faq'
import { Route as publicEventsRouteImport } from './routes/(public)/events'
import { Route as publicBlogRouteImport } from './routes/(public)/blog'
import { Route as AppVendorWatchIndexRouteImport } from './routes/_app/vendor-watch.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers.index'
import { Route as AppContentIndexRouteImport } from './routes/_app/content.index'
import { Route as AppBatchesIndexRouteImport } from './routes/_app/batches.index'
import { Route as AppVendorWatchSourceIdRouteImport } from './routes/_app/vendor-watch.$sourceId'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings.users'
import { Route as AppSettingsMetaRouteImport } from './routes/_app/settings.meta'
import { Route as AppSettingsLoyaltyRouteImport } from './routes/_app/settings.loyalty'
import { Route as AppSettingsCloverRouteImport } from './routes/_app/settings.clover'
import { Route as AppSettingsAiRouteImport } from './routes/_app/settings.ai'
import { Route as AppInventoryTradeInRouteImport } from './routes/_app/inventory.trade-in'
import { Route as AppInventoryRestockRouteImport } from './routes/_app/inventory.restock'
import { Route as AppInventoryMissingTagsRouteImport } from './routes/_app/inventory.missing-tags'
import { Route as AppInventoryCountRouteImport } from './routes/_app/inventory.count'
import { Route as AppInventoryCoralDiscoveryRouteImport } from './routes/_app/inventory.coral-discovery'
import { Route as AppInventoryCloverReconcileRouteImport } from './routes/_app/inventory.clover-reconcile'
import { Route as AppInventoryIdRouteImport } from './routes/_app/inventory.$id'
import { Route as AppCustomersIdRouteImport } from './routes/_app/customers.$id'
import { Route as AppContentNewRouteImport } from './routes/_app/content.new'
import { Route as AppContentIdRouteImport } from './routes/_app/content.$id'
import { Route as AppBatchesIdRouteImport } from './routes/_app/batches.$id'
import { Route as publicProductsSlugRouteImport } from './routes/(public)/products.$slug'
import { Route as publicGuidesSlugRouteImport } from './routes/(public)/guides.$slug'
import { Route as publicCollectionsSlugRouteImport } from './routes/(public)/collections.$slug'
import { Route as publicBlogSlugRouteImport } from './routes/(public)/blog.$slug'
import { Route as ApiPublicHooksRefreshScrapeSourcesRouteImport } from './routes/api/public/hooks/refresh-scrape-sources'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreLocationsRoute = AppStoreLocationsRouteImport.update({
  id: '/store-locations',
  path: '/store-locations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishingRoute = AppPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingApprovalRoute = AppPricingApprovalRouteImport.update({
  id: '/pricing-approval',
  path: '/pricing-approval',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesRoute = AppBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AppRoute,
} as any)
const publicVisitRoute = publicVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicShopRoute = publicShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicGuidesRoute = publicGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicFaqRoute = publicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicEventsRoute = publicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicBlogRoute = publicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => publicRouteRoute,
} as any)
const AppVendorWatchIndexRoute = AppVendorWatchIndexRouteImport.update({
  id: '/vendor-watch/',
  path: '/vendor-watch/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppContentIndexRoute = AppContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIndexRoute = AppBatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBatchesRoute,
} as any)
const AppVendorWatchSourceIdRoute = AppVendorWatchSourceIdRouteImport.update({
  id: '/vendor-watch/$sourceId',
  path: '/vendor-watch/$sourceId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMetaRoute = AppSettingsMetaRouteImport.update({
  id: '/settings/meta',
  path: '/settings/meta',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLoyaltyRoute = AppSettingsLoyaltyRouteImport.update({
  id: '/settings/loyalty',
  path: '/settings/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCloverRoute = AppSettingsCloverRouteImport.update({
  id: '/settings/clover',
  path: '/settings/clover',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryTradeInRoute = AppInventoryTradeInRouteImport.update({
  id: '/trade-in',
  path: '/trade-in',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryRestockRoute = AppInventoryRestockRouteImport.update({
  id: '/restock',
  path: '/restock',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMissingTagsRoute = AppInventoryMissingTagsRouteImport.update({
  id: '/missing-tags',
  path: '/missing-tags',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryCountRoute = AppInventoryCountRouteImport.update({
  id: '/count',
  path: '/count',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryCoralDiscoveryRoute =
  AppInventoryCoralDiscoveryRouteImport.update({
    id: '/coral-discovery',
    path: '/coral-discovery',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryCloverReconcileRoute =
  AppInventoryCloverReconcileRouteImport.update({
    id: '/clover-reconcile',
    path: '/clover-reconcile',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryIdRoute = AppInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContentNewRoute = AppContentNewRouteImport.update({
  id: '/content/new',
  path: '/content/new',
  getParentRoute: () => AppRoute,
} as any)
const AppContentIdRoute = AppContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIdRoute = AppBatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBatchesRoute,
} as any)
const publicProductsSlugRoute = publicProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicGuidesSlugRoute = publicGuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => publicGuidesRoute,
} as any)
const publicCollectionsSlugRoute = publicCollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicBlogSlugRoute = publicBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => publicBlogRoute,
} as any)
const ApiPublicHooksRefreshScrapeSourcesRoute =
  ApiPublicHooksRefreshScrapeSourcesRouteImport.update({
    id: '/api/public/hooks/refresh-scrape-sources',
    path: '/api/public/hooks/refresh-scrape-sources',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/blog': typeof publicBlogRouteWithChildren
  '/events': typeof publicEventsRoute
  '/faq': typeof publicFaqRoute
  '/guides': typeof publicGuidesRouteWithChildren
  '/shop': typeof publicShopRoute
  '/visit': typeof publicVisitRoute
  '/batches': typeof AppBatchesRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/media': typeof AppMediaRoute
  '/pricing-approval': typeof AppPricingApprovalRoute
  '/products': typeof AppProductsRoute
  '/publishing': typeof AppPublishingRoute
  '/reports': typeof AppReportsRoute
  '/store-locations': typeof AppStoreLocationsRoute
  '/tasks': typeof AppTasksRoute
  '/vendors': typeof AppVendorsRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/collections/$slug': typeof publicCollectionsSlugRoute
  '/guides/$slug': typeof publicGuidesSlugRoute
  '/products/$slug': typeof publicProductsSlugRoute
  '/batches/$id': typeof AppBatchesIdRoute
  '/content/$id': typeof AppContentIdRoute
  '/content/new': typeof AppContentNewRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/inventory/clover-reconcile': typeof AppInventoryCloverReconcileRoute
  '/inventory/coral-discovery': typeof AppInventoryCoralDiscoveryRoute
  '/inventory/count': typeof AppInventoryCountRoute
  '/inventory/missing-tags': typeof AppInventoryMissingTagsRoute
  '/inventory/restock': typeof AppInventoryRestockRoute
  '/inventory/trade-in': typeof AppInventoryTradeInRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/clover': typeof AppSettingsCloverRoute
  '/settings/loyalty': typeof AppSettingsLoyaltyRoute
  '/settings/meta': typeof AppSettingsMetaRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/vendor-watch/$sourceId': typeof AppVendorWatchSourceIdRoute
  '/batches/': typeof AppBatchesIndexRoute
  '/content/': typeof AppContentIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/vendor-watch/': typeof AppVendorWatchIndexRoute
  '/api/public/hooks/refresh-scrape-sources': typeof ApiPublicHooksRefreshScrapeSourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/blog': typeof publicBlogRouteWithChildren
  '/events': typeof publicEventsRoute
  '/faq': typeof publicFaqRoute
  '/guides': typeof publicGuidesRouteWithChildren
  '/shop': typeof publicShopRoute
  '/visit': typeof publicVisitRoute
  '/calendar': typeof AppCalendarRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/media': typeof AppMediaRoute
  '/pricing-approval': typeof AppPricingApprovalRoute
  '/products': typeof AppProductsRoute
  '/publishing': typeof AppPublishingRoute
  '/reports': typeof AppReportsRoute
  '/store-locations': typeof AppStoreLocationsRoute
  '/tasks': typeof AppTasksRoute
  '/vendors': typeof AppVendorsRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/collections/$slug': typeof publicCollectionsSlugRoute
  '/guides/$slug': typeof publicGuidesSlugRoute
  '/products/$slug': typeof publicProductsSlugRoute
  '/batches/$id': typeof AppBatchesIdRoute
  '/content/$id': typeof AppContentIdRoute
  '/content/new': typeof AppContentNewRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/inventory/clover-reconcile': typeof AppInventoryCloverReconcileRoute
  '/inventory/coral-discovery': typeof AppInventoryCoralDiscoveryRoute
  '/inventory/count': typeof AppInventoryCountRoute
  '/inventory/missing-tags': typeof AppInventoryMissingTagsRoute
  '/inventory/restock': typeof AppInventoryRestockRoute
  '/inventory/trade-in': typeof AppInventoryTradeInRoute
  '/settings/ai': typeof AppSettingsAiRoute
  '/settings/clover': typeof AppSettingsCloverRoute
  '/settings/loyalty': typeof AppSettingsLoyaltyRoute
  '/settings/meta': typeof AppSettingsMetaRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/vendor-watch/$sourceId': typeof AppVendorWatchSourceIdRoute
  '/batches': typeof AppBatchesIndexRoute
  '/content': typeof AppContentIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/vendor-watch': typeof AppVendorWatchIndexRoute
  '/api/public/hooks/refresh-scrape-sources': typeof ApiPublicHooksRefreshScrapeSourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/(public)/blog': typeof publicBlogRouteWithChildren
  '/(public)/events': typeof publicEventsRoute
  '/(public)/faq': typeof publicFaqRoute
  '/(public)/guides': typeof publicGuidesRouteWithChildren
  '/(public)/shop': typeof publicShopRoute
  '/(public)/visit': typeof publicVisitRoute
  '/_app/batches': typeof AppBatchesRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/media': typeof AppMediaRoute
  '/_app/pricing-approval': typeof AppPricingApprovalRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/publishing': typeof AppPublishingRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/store-locations': typeof AppStoreLocationsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/blog/$slug': typeof publicBlogSlugRoute
  '/(public)/collections/$slug': typeof publicCollectionsSlugRoute
  '/(public)/guides/$slug': typeof publicGuidesSlugRoute
  '/(public)/products/$slug': typeof publicProductsSlugRoute
  '/_app/batches/$id': typeof AppBatchesIdRoute
  '/_app/content/$id': typeof AppContentIdRoute
  '/_app/content/new': typeof AppContentNewRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/inventory/$id': typeof AppInventoryIdRoute
  '/_app/inventory/clover-reconcile': typeof AppInventoryCloverReconcileRoute
  '/_app/inventory/coral-discovery': typeof AppInventoryCoralDiscoveryRoute
  '/_app/inventory/count': typeof AppInventoryCountRoute
  '/_app/inventory/missing-tags': typeof AppInventoryMissingTagsRoute
  '/_app/inventory/restock': typeof AppInventoryRestockRoute
  '/_app/inventory/trade-in': typeof AppInventoryTradeInRoute
  '/_app/settings/ai': typeof AppSettingsAiRoute
  '/_app/settings/clover': typeof AppSettingsCloverRoute
  '/_app/settings/loyalty': typeof AppSettingsLoyaltyRoute
  '/_app/settings/meta': typeof AppSettingsMetaRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/vendor-watch/$sourceId': typeof AppVendorWatchSourceIdRoute
  '/_app/batches/': typeof AppBatchesIndexRoute
  '/_app/content/': typeof AppContentIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/vendor-watch/': typeof AppVendorWatchIndexRoute
  '/api/public/hooks/refresh-scrape-sources': typeof ApiPublicHooksRefreshScrapeSourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/blog'
    | '/events'
    | '/faq'
    | '/guides'
    | '/shop'
    | '/visit'
    | '/batches'
    | '/calendar'
    | '/campaigns'
    | '/dashboard'
    | '/inventory'
    | '/media'
    | '/pricing-approval'
    | '/products'
    | '/publishing'
    | '/reports'
    | '/store-locations'
    | '/tasks'
    | '/vendors'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/guides/$slug'
    | '/products/$slug'
    | '/batches/$id'
    | '/content/$id'
    | '/content/new'
    | '/customers/$id'
    | '/inventory/$id'
    | '/inventory/clover-reconcile'
    | '/inventory/coral-discovery'
    | '/inventory/count'
    | '/inventory/missing-tags'
    | '/inventory/restock'
    | '/inventory/trade-in'
    | '/settings/ai'
    | '/settings/clover'
    | '/settings/loyalty'
    | '/settings/meta'
    | '/settings/users'
    | '/vendor-watch/$sourceId'
    | '/batches/'
    | '/content/'
    | '/customers/'
    | '/inventory/'
    | '/vendor-watch/'
    | '/api/public/hooks/refresh-scrape-sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/blog'
    | '/events'
    | '/faq'
    | '/guides'
    | '/shop'
    | '/visit'
    | '/calendar'
    | '/campaigns'
    | '/dashboard'
    | '/media'
    | '/pricing-approval'
    | '/products'
    | '/publishing'
    | '/reports'
    | '/store-locations'
    | '/tasks'
    | '/vendors'
    | '/blog/$slug'
    | '/collections/$slug'
    | '/guides/$slug'
    | '/products/$slug'
    | '/batches/$id'
    | '/content/$id'
    | '/content/new'
    | '/customers/$id'
    | '/inventory/$id'
    | '/inventory/clover-reconcile'
    | '/inventory/coral-discovery'
    | '/inventory/count'
    | '/inventory/missing-tags'
    | '/inventory/restock'
    | '/inventory/trade-in'
    | '/settings/ai'
    | '/settings/clover'
    | '/settings/loyalty'
    | '/settings/meta'
    | '/settings/users'
    | '/vendor-watch/$sourceId'
    | '/batches'
    | '/content'
    | '/customers'
    | '/inventory'
    | '/vendor-watch'
    | '/api/public/hooks/refresh-scrape-sources'
  id:
    | '__root__'
    | '/(public)'
    | '/_app'
    | '/catalog'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/(public)/blog'
    | '/(public)/events'
    | '/(public)/faq'
    | '/(public)/guides'
    | '/(public)/shop'
    | '/(public)/visit'
    | '/_app/batches'
    | '/_app/calendar'
    | '/_app/campaigns'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/media'
    | '/_app/pricing-approval'
    | '/_app/products'
    | '/_app/publishing'
    | '/_app/reports'
    | '/_app/store-locations'
    | '/_app/tasks'
    | '/_app/vendors'
    | '/(public)/'
    | '/(public)/blog/$slug'
    | '/(public)/collections/$slug'
    | '/(public)/guides/$slug'
    | '/(public)/products/$slug'
    | '/_app/batches/$id'
    | '/_app/content/$id'
    | '/_app/content/new'
    | '/_app/customers/$id'
    | '/_app/inventory/$id'
    | '/_app/inventory/clover-reconcile'
    | '/_app/inventory/coral-discovery'
    | '/_app/inventory/count'
    | '/_app/inventory/missing-tags'
    | '/_app/inventory/restock'
    | '/_app/inventory/trade-in'
    | '/_app/settings/ai'
    | '/_app/settings/clover'
    | '/_app/settings/loyalty'
    | '/_app/settings/meta'
    | '/_app/settings/users'
    | '/_app/vendor-watch/$sourceId'
    | '/_app/batches/'
    | '/_app/content/'
    | '/_app/customers/'
    | '/_app/inventory/'
    | '/_app/vendor-watch/'
    | '/api/public/hooks/refresh-scrape-sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksRefreshScrapeSourcesRoute: typeof ApiPublicHooksRefreshScrapeSourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store-locations': {
      id: '/_app/store-locations'
      path: '/store-locations'
      fullPath: '/store-locations'
      preLoaderRoute: typeof AppStoreLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publishing': {
      id: '/_app/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof AppPublishingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing-approval': {
      id: '/_app/pricing-approval'
      path: '/pricing-approval'
      fullPath: '/pricing-approval'
      preLoaderRoute: typeof AppPricingApprovalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/batches': {
      id: '/_app/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AppBatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/(public)/visit': {
      id: '/(public)/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof publicVisitRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/shop': {
      id: '/(public)/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof publicShopRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/guides': {
      id: '/(public)/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof publicGuidesRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/faq': {
      id: '/(public)/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof publicFaqRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/events': {
      id: '/(public)/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof publicEventsRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/blog': {
      id: '/(public)/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof publicBlogRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/_app/vendor-watch/': {
      id: '/_app/vendor-watch/'
      path: '/vendor-watch'
      fullPath: '/vendor-watch/'
      preLoaderRoute: typeof AppVendorWatchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/': {
      id: '/_app/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof AppContentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/batches/': {
      id: '/_app/batches/'
      path: '/'
      fullPath: '/batches/'
      preLoaderRoute: typeof AppBatchesIndexRouteImport
      parentRoute: typeof AppBatchesRoute
    }
    '/_app/vendor-watch/$sourceId': {
      id: '/_app/vendor-watch/$sourceId'
      path: '/vendor-watch/$sourceId'
      fullPath: '/vendor-watch/$sourceId'
      preLoaderRoute: typeof AppVendorWatchSourceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/meta': {
      id: '/_app/settings/meta'
      path: '/settings/meta'
      fullPath: '/settings/meta'
      preLoaderRoute: typeof AppSettingsMetaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/loyalty': {
      id: '/_app/settings/loyalty'
      path: '/settings/loyalty'
      fullPath: '/settings/loyalty'
      preLoaderRoute: typeof AppSettingsLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/clover': {
      id: '/_app/settings/clover'
      path: '/settings/clover'
      fullPath: '/settings/clover'
      preLoaderRoute: typeof AppSettingsCloverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/ai': {
      id: '/_app/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/trade-in': {
      id: '/_app/inventory/trade-in'
      path: '/trade-in'
      fullPath: '/inventory/trade-in'
      preLoaderRoute: typeof AppInventoryTradeInRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/restock': {
      id: '/_app/inventory/restock'
      path: '/restock'
      fullPath: '/inventory/restock'
      preLoaderRoute: typeof AppInventoryRestockRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/missing-tags': {
      id: '/_app/inventory/missing-tags'
      path: '/missing-tags'
      fullPath: '/inventory/missing-tags'
      preLoaderRoute: typeof AppInventoryMissingTagsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/count': {
      id: '/_app/inventory/count'
      path: '/count'
      fullPath: '/inventory/count'
      preLoaderRoute: typeof AppInventoryCountRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/coral-discovery': {
      id: '/_app/inventory/coral-discovery'
      path: '/coral-discovery'
      fullPath: '/inventory/coral-discovery'
      preLoaderRoute: typeof AppInventoryCoralDiscoveryRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/clover-reconcile': {
      id: '/_app/inventory/clover-reconcile'
      path: '/clover-reconcile'
      fullPath: '/inventory/clover-reconcile'
      preLoaderRoute: typeof AppInventoryCloverReconcileRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/$id': {
      id: '/_app/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AppInventoryIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/new': {
      id: '/_app/content/new'
      path: '/content/new'
      fullPath: '/content/new'
      preLoaderRoute: typeof AppContentNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/$id': {
      id: '/_app/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof AppContentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/batches/$id': {
      id: '/_app/batches/$id'
      path: '/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof AppBatchesIdRouteImport
      parentRoute: typeof AppBatchesRoute
    }
    '/(public)/products/$slug': {
      id: '/(public)/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof publicProductsSlugRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/guides/$slug': {
      id: '/(public)/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof publicGuidesSlugRouteImport
      parentRoute: typeof publicGuidesRoute
    }
    '/(public)/collections/$slug': {
      id: '/(public)/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof publicCollectionsSlugRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/blog/$slug': {
      id: '/(public)/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof publicBlogSlugRouteImport
      parentRoute: typeof publicBlogRoute
    }
    '/api/public/hooks/refresh-scrape-sources': {
      id: '/api/public/hooks/refresh-scrape-sources'
      path: '/api/public/hooks/refresh-scrape-sources'
      fullPath: '/api/public/hooks/refresh-scrape-sources'
      preLoaderRoute: typeof ApiPublicHooksRefreshScrapeSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface publicBlogRouteChildren {
  publicBlogSlugRoute: typeof publicBlogSlugRoute
}

const publicBlogRouteChildren: publicBlogRouteChildren = {
  publicBlogSlugRoute: publicBlogSlugRoute,
}

const publicBlogRouteWithChildren = publicBlogRoute._addFileChildren(
  publicBlogRouteChildren,
)

interface publicGuidesRouteChildren {
  publicGuidesSlugRoute: typeof publicGuidesSlugRoute
}

const publicGuidesRouteChildren: publicGuidesRouteChildren = {
  publicGuidesSlugRoute: publicGuidesSlugRoute,
}

const publicGuidesRouteWithChildren = publicGuidesRoute._addFileChildren(
  publicGuidesRouteChildren,
)

interface publicRouteRouteChildren {
  publicBlogRoute: typeof publicBlogRouteWithChildren
  publicEventsRoute: typeof publicEventsRoute
  publicFaqRoute: typeof publicFaqRoute
  publicGuidesRoute: typeof publicGuidesRouteWithChildren
  publicShopRoute: typeof publicShopRoute
  publicVisitRoute: typeof publicVisitRoute
  publicIndexRoute: typeof publicIndexRoute
  publicCollectionsSlugRoute: typeof publicCollectionsSlugRoute
  publicProductsSlugRoute: typeof publicProductsSlugRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicBlogRoute: publicBlogRouteWithChildren,
  publicEventsRoute: publicEventsRoute,
  publicFaqRoute: publicFaqRoute,
  publicGuidesRoute: publicGuidesRouteWithChildren,
  publicShopRoute: publicShopRoute,
  publicVisitRoute: publicVisitRoute,
  publicIndexRoute: publicIndexRoute,
  publicCollectionsSlugRoute: publicCollectionsSlugRoute,
  publicProductsSlugRoute: publicProductsSlugRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface AppBatchesRouteChildren {
  AppBatchesIdRoute: typeof AppBatchesIdRoute
  AppBatchesIndexRoute: typeof AppBatchesIndexRoute
}

const AppBatchesRouteChildren: AppBatchesRouteChildren = {
  AppBatchesIdRoute: AppBatchesIdRoute,
  AppBatchesIndexRoute: AppBatchesIndexRoute,
}

const AppBatchesRouteWithChildren = AppBatchesRoute._addFileChildren(
  AppBatchesRouteChildren,
)

interface AppInventoryRouteChildren {
  AppInventoryIdRoute: typeof AppInventoryIdRoute
  AppInventoryCloverReconcileRoute: typeof AppInventoryCloverReconcileRoute
  AppInventoryCoralDiscoveryRoute: typeof AppInventoryCoralDiscoveryRoute
  AppInventoryCountRoute: typeof AppInventoryCountRoute
  AppInventoryMissingTagsRoute: typeof AppInventoryMissingTagsRoute
  AppInventoryRestockRoute: typeof AppInventoryRestockRoute
  AppInventoryTradeInRoute: typeof AppInventoryTradeInRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryIdRoute: AppInventoryIdRoute,
  AppInventoryCloverReconcileRoute: AppInventoryCloverReconcileRoute,
  AppInventoryCoralDiscoveryRoute: AppInventoryCoralDiscoveryRoute,
  AppInventoryCountRoute: AppInventoryCountRoute,
  AppInventoryMissingTagsRoute: AppInventoryMissingTagsRoute,
  AppInventoryRestockRoute: AppInventoryRestockRoute,
  AppInventoryTradeInRoute: AppInventoryTradeInRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppRouteChildren {
  AppBatchesRoute: typeof AppBatchesRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppMediaRoute: typeof AppMediaRoute
  AppPricingApprovalRoute: typeof AppPricingApprovalRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPublishingRoute: typeof AppPublishingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppStoreLocationsRoute: typeof AppStoreLocationsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppContentIdRoute: typeof AppContentIdRoute
  AppContentNewRoute: typeof AppContentNewRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsCloverRoute: typeof AppSettingsCloverRoute
  AppSettingsLoyaltyRoute: typeof AppSettingsLoyaltyRoute
  AppSettingsMetaRoute: typeof AppSettingsMetaRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppVendorWatchSourceIdRoute: typeof AppVendorWatchSourceIdRoute
  AppContentIndexRoute: typeof AppContentIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppVendorWatchIndexRoute: typeof AppVendorWatchIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBatchesRoute: AppBatchesRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppMediaRoute: AppMediaRoute,
  AppPricingApprovalRoute: AppPricingApprovalRoute,
  AppProductsRoute: AppProductsRoute,
  AppPublishingRoute: AppPublishingRoute,
  AppReportsRoute: AppReportsRoute,
  AppStoreLocationsRoute: AppStoreLocationsRoute,
  AppTasksRoute: AppTasksRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppContentIdRoute: AppContentIdRoute,
  AppContentNewRoute: AppContentNewRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsCloverRoute: AppSettingsCloverRoute,
  AppSettingsLoyaltyRoute: AppSettingsLoyaltyRoute,
  AppSettingsMetaRoute: AppSettingsMetaRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppVendorWatchSourceIdRoute: AppVendorWatchSourceIdRoute,
  AppContentIndexRoute: AppContentIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppVendorWatchIndexRoute: AppVendorWatchIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CatalogRoute: CatalogRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksRefreshScrapeSourcesRoute:
    ApiPublicHooksRefreshScrapeSourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
