/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendorsRouteImport } from './routes/_app/vendors'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppStoreLocationsRouteImport } from './routes/_app/store-locations'
import { Route as AppPublishingRouteImport } from './routes/_app/publishing'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppPricingApprovalRouteImport } from './routes/_app/pricing-approval'
import { Route as AppMediaRouteImport } from './routes/_app/media'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBatchesRouteImport } from './routes/_app/batches'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory.index'
import { Route as AppContentIndexRouteImport } from './routes/_app/content.index'
import { Route as AppBatchesIndexRouteImport } from './routes/_app/batches.index'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings.users'
import { Route as AppSettingsMetaRouteImport } from './routes/_app/settings.meta'
import { Route as AppInventoryIdRouteImport } from './routes/_app/inventory.$id'
import { Route as AppContentNewRouteImport } from './routes/_app/content.new'
import { Route as AppContentIdRouteImport } from './routes/_app/content.$id'
import { Route as AppBatchesIdRouteImport } from './routes/_app/batches.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreLocationsRoute = AppStoreLocationsRouteImport.update({
  id: '/store-locations',
  path: '/store-locations',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishingRoute = AppPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingApprovalRoute = AppPricingApprovalRouteImport.update({
  id: '/pricing-approval',
  path: '/pricing-approval',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesRoute = AppBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppContentIndexRoute = AppContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIndexRoute = AppBatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBatchesRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMetaRoute = AppSettingsMetaRouteImport.update({
  id: '/settings/meta',
  path: '/settings/meta',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIdRoute = AppInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppContentNewRoute = AppContentNewRouteImport.update({
  id: '/content/new',
  path: '/content/new',
  getParentRoute: () => AppRoute,
} as any)
const AppContentIdRoute = AppContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIdRoute = AppBatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppBatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/batches': typeof AppBatchesRouteWithChildren
  '/calendar': typeof AppCalendarRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/media': typeof AppMediaRoute
  '/pricing-approval': typeof AppPricingApprovalRoute
  '/products': typeof AppProductsRoute
  '/publishing': typeof AppPublishingRoute
  '/store-locations': typeof AppStoreLocationsRoute
  '/tasks': typeof AppTasksRoute
  '/vendors': typeof AppVendorsRoute
  '/batches/$id': typeof AppBatchesIdRoute
  '/content/$id': typeof AppContentIdRoute
  '/content/new': typeof AppContentNewRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/settings/meta': typeof AppSettingsMetaRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/batches/': typeof AppBatchesIndexRoute
  '/content/': typeof AppContentIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AppCalendarRoute
  '/campaigns': typeof AppCampaignsRoute
  '/dashboard': typeof AppDashboardRoute
  '/media': typeof AppMediaRoute
  '/pricing-approval': typeof AppPricingApprovalRoute
  '/products': typeof AppProductsRoute
  '/publishing': typeof AppPublishingRoute
  '/store-locations': typeof AppStoreLocationsRoute
  '/tasks': typeof AppTasksRoute
  '/vendors': typeof AppVendorsRoute
  '/batches/$id': typeof AppBatchesIdRoute
  '/content/$id': typeof AppContentIdRoute
  '/content/new': typeof AppContentNewRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/settings/meta': typeof AppSettingsMetaRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/batches': typeof AppBatchesIndexRoute
  '/content': typeof AppContentIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/signup': typeof SignupRoute
  '/_app/batches': typeof AppBatchesRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/media': typeof AppMediaRoute
  '/_app/pricing-approval': typeof AppPricingApprovalRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/publishing': typeof AppPublishingRoute
  '/_app/store-locations': typeof AppStoreLocationsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/batches/$id': typeof AppBatchesIdRoute
  '/_app/content/$id': typeof AppContentIdRoute
  '/_app/content/new': typeof AppContentNewRoute
  '/_app/inventory/$id': typeof AppInventoryIdRoute
  '/_app/settings/meta': typeof AppSettingsMetaRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/batches/': typeof AppBatchesIndexRoute
  '/_app/content/': typeof AppContentIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/batches'
    | '/calendar'
    | '/campaigns'
    | '/dashboard'
    | '/inventory'
    | '/media'
    | '/pricing-approval'
    | '/products'
    | '/publishing'
    | '/store-locations'
    | '/tasks'
    | '/vendors'
    | '/batches/$id'
    | '/content/$id'
    | '/content/new'
    | '/inventory/$id'
    | '/settings/meta'
    | '/settings/users'
    | '/batches/'
    | '/content/'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/calendar'
    | '/campaigns'
    | '/dashboard'
    | '/media'
    | '/pricing-approval'
    | '/products'
    | '/publishing'
    | '/store-locations'
    | '/tasks'
    | '/vendors'
    | '/batches/$id'
    | '/content/$id'
    | '/content/new'
    | '/inventory/$id'
    | '/settings/meta'
    | '/settings/users'
    | '/batches'
    | '/content'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pending-approval'
    | '/signup'
    | '/_app/batches'
    | '/_app/calendar'
    | '/_app/campaigns'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/media'
    | '/_app/pricing-approval'
    | '/_app/products'
    | '/_app/publishing'
    | '/_app/store-locations'
    | '/_app/tasks'
    | '/_app/vendors'
    | '/_app/batches/$id'
    | '/_app/content/$id'
    | '/_app/content/new'
    | '/_app/inventory/$id'
    | '/_app/settings/meta'
    | '/_app/settings/users'
    | '/_app/batches/'
    | '/_app/content/'
    | '/_app/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store-locations': {
      id: '/_app/store-locations'
      path: '/store-locations'
      fullPath: '/store-locations'
      preLoaderRoute: typeof AppStoreLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/publishing': {
      id: '/_app/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof AppPublishingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing-approval': {
      id: '/_app/pricing-approval'
      path: '/pricing-approval'
      fullPath: '/pricing-approval'
      preLoaderRoute: typeof AppPricingApprovalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/batches': {
      id: '/_app/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AppBatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/content/': {
      id: '/_app/content/'
      path: '/content'
      fullPath: '/content/'
      preLoaderRoute: typeof AppContentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/batches/': {
      id: '/_app/batches/'
      path: '/'
      fullPath: '/batches/'
      preLoaderRoute: typeof AppBatchesIndexRouteImport
      parentRoute: typeof AppBatchesRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/meta': {
      id: '/_app/settings/meta'
      path: '/settings/meta'
      fullPath: '/settings/meta'
      preLoaderRoute: typeof AppSettingsMetaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/$id': {
      id: '/_app/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AppInventoryIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/content/new': {
      id: '/_app/content/new'
      path: '/content/new'
      fullPath: '/content/new'
      preLoaderRoute: typeof AppContentNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content/$id': {
      id: '/_app/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof AppContentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/batches/$id': {
      id: '/_app/batches/$id'
      path: '/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof AppBatchesIdRouteImport
      parentRoute: typeof AppBatchesRoute
    }
  }
}

interface AppBatchesRouteChildren {
  AppBatchesIdRoute: typeof AppBatchesIdRoute
  AppBatchesIndexRoute: typeof AppBatchesIndexRoute
}

const AppBatchesRouteChildren: AppBatchesRouteChildren = {
  AppBatchesIdRoute: AppBatchesIdRoute,
  AppBatchesIndexRoute: AppBatchesIndexRoute,
}

const AppBatchesRouteWithChildren = AppBatchesRoute._addFileChildren(
  AppBatchesRouteChildren,
)

interface AppInventoryRouteChildren {
  AppInventoryIdRoute: typeof AppInventoryIdRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryIdRoute: AppInventoryIdRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppRouteChildren {
  AppBatchesRoute: typeof AppBatchesRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppMediaRoute: typeof AppMediaRoute
  AppPricingApprovalRoute: typeof AppPricingApprovalRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPublishingRoute: typeof AppPublishingRoute
  AppStoreLocationsRoute: typeof AppStoreLocationsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppContentIdRoute: typeof AppContentIdRoute
  AppContentNewRoute: typeof AppContentNewRoute
  AppSettingsMetaRoute: typeof AppSettingsMetaRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppContentIndexRoute: typeof AppContentIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBatchesRoute: AppBatchesRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppMediaRoute: AppMediaRoute,
  AppPricingApprovalRoute: AppPricingApprovalRoute,
  AppProductsRoute: AppProductsRoute,
  AppPublishingRoute: AppPublishingRoute,
  AppStoreLocationsRoute: AppStoreLocationsRoute,
  AppTasksRoute: AppTasksRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppContentIdRoute: AppContentIdRoute,
  AppContentNewRoute: AppContentNewRoute,
  AppSettingsMetaRoute: AppSettingsMetaRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppContentIndexRoute: AppContentIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
